---
name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'criteo/mesosbuild.git'
          ref: master
      - name: Build the Docker image
        run: docker build .
          --file Dockerfile.automake
          --tag mesosbuild:"$GITHUB_SHA"
          --build-arg MESOS_VERSION="$GITHUB_SHA"
          --build-arg MESOS_GIT="https://github.com/${{ github.repository }}"
          --build-arg CONFIGURE_EXTRA_FLAGS="--enable-test-only-regression"
      - name: Test mesos
        run: docker run
          -e GTEST_FILTER='-EnvironmentSecretIsolatorTest.*:ExamplesTest.DiskFullFramework:ContainerizerTest.ROOT_CGROUPS_BalloonFramework'
          mesosbuild:"$GITHUB_SHA"
          make check -j $(nproc)
